import { CommitInfo, RepoMetadata } from './types';

export const DEMO_REPOS: Record<string, { metadata: RepoMetadata; commits: CommitInfo[] }> = {
  'vercel/swr': {
    metadata: {
      owner: 'vercel',
      repo: 'swr',
      description: 'React Hooks for Data Fetching',
      stars: 30400,
      forks: 1400,
      defaultBranch: 'main',
      language: 'TypeScript',
    },
    commits: [
      {
        sha: 'c1a010101',
        shortSha: 'c1a0101',
        author: { name: 'Shu Ding', avatarUrl: 'https://avatars.githubusercontent.com/u/3676859' },
        date: '2023-01-10T10:00:00Z',
        message: 'feat: initial core hook layout',
        filesChanged: [
          { filename: 'src/index.ts', status: 'added', additions: 140, deletions: 0, changes: 140 },
          { filename: 'src/use-swr.ts', status: 'added', additions: 320, deletions: 0, changes: 320 },
          { filename: 'src/types.ts', status: 'added', additions: 110, deletions: 0, changes: 110 },
          { filename: 'package.json', status: 'added', additions: 45, deletions: 0, changes: 45 },
          { filename: 'README.md', status: 'added', additions: 80, deletions: 0, changes: 80 },
        ],
      },
      {
        sha: 'c2b020202',
        shortSha: 'c2b0202',
        author: { name: 'Paco Coursey', avatarUrl: 'https://avatars.githubusercontent.com/u/34928425' },
        date: '2023-02-15T14:30:00Z',
        message: 'feat(mutation): add optimistic ui support & cache utils',
        filesChanged: [
          { filename: 'src/mutate.ts', status: 'added', additions: 220, deletions: 0, changes: 220 },
          { filename: 'src/use-swr.ts', status: 'modified', additions: 85, deletions: 20, changes: 105 },
          { filename: 'src/utils/cache.ts', status: 'added', additions: 160, deletions: 0, changes: 160 },
          { filename: 'src/utils/hash.ts', status: 'added', additions: 75, deletions: 0, changes: 75 },
          { filename: 'tests/mutate.test.ts', status: 'added', additions: 190, deletions: 0, changes: 190 },
        ],
      },
      {
        sha: 'c3c030303',
        shortSha: 'c3c0303',
        author: { name: 'Jiachi Liu', avatarUrl: 'https://avatars.githubusercontent.com/u/4800338' },
        date: '2023-03-20T18:10:00Z',
        message: 'feat(infinite): support paginated and infinite scroll hooks',
        filesChanged: [
          { filename: 'src/infinite/index.ts', status: 'added', additions: 280, deletions: 0, changes: 280 },
          { filename: 'src/infinite/types.ts', status: 'added', additions: 90, deletions: 0, changes: 90 },
          { filename: 'src/types.ts', status: 'modified', additions: 40, deletions: 5, changes: 45 },
          { filename: 'tests/infinite.test.ts', status: 'added', additions: 240, deletions: 0, changes: 240 },
        ],
      },
      {
        sha: 'c4d040404',
        shortSha: 'c4d0404',
        author: { name: 'Shu Ding', avatarUrl: 'https://avatars.githubusercontent.com/u/3676859' },
        date: '2023-05-12T09:00:00Z',
        message: 'refactor: split subscription and web socket listeners',
        filesChanged: [
          { filename: 'src/subscription/index.ts', status: 'added', additions: 180, deletions: 0, changes: 180 },
          { filename: 'src/utils/web-preset.ts', status: 'added', additions: 130, deletions: 0, changes: 130 },
          { filename: 'src/use-swr.ts', status: 'modified', additions: 30, deletions: 60, changes: 90 },
          { filename: 'src/utils/hash.ts', status: 'removed', additions: 0, deletions: 75, changes: 75 },
        ],
      },
      {
        sha: 'c5e050505',
        shortSha: 'c5e0505',
        author: { name: 'Guillermo Rauch', avatarUrl: 'https://avatars.githubusercontent.com/u/13041' },
        date: '2023-08-01T16:45:00Z',
        message: 'docs: modernize architecture guides and benchmarks',
        filesChanged: [
          { filename: 'docs/architecture.md', status: 'added', additions: 310, deletions: 0, changes: 310 },
          { filename: 'docs/benchmarks.md', status: 'added', additions: 195, deletions: 0, changes: 195 },
          { filename: 'README.md', status: 'modified', additions: 60, deletions: 15, changes: 75 },
          { filename: 'package.json', status: 'modified', additions: 12, deletions: 4, changes: 16 },
        ],
      },
      {
        sha: 'c6f060606',
        shortSha: 'c6f0606',
        author: { name: 'Shu Ding', avatarUrl: 'https://avatars.githubusercontent.com/u/3676859' },
        date: '2023-11-20T11:20:00Z',
        message: 'feat(server): support React 19 RSC and server actions prefetch',
        filesChanged: [
          { filename: 'src/server/index.ts', status: 'added', additions: 340, deletions: 0, changes: 340 },
          { filename: 'src/server/preload.ts', status: 'added', additions: 175, deletions: 0, changes: 175 },
          { filename: 'src/types.ts', status: 'modified', additions: 65, deletions: 10, changes: 75 },
          { filename: 'tests/rsc.test.ts', status: 'added', additions: 210, deletions: 0, changes: 210 },
        ],
      },
    ],
  },
  'expressjs/express': {
    metadata: {
      owner: 'expressjs',
      repo: 'express',
      description: 'Fast, unopinionated, minimalist web framework for node.',
      stars: 64500,
      forks: 16000,
      defaultBranch: 'master',
      language: 'JavaScript',
    },
    commits: [
      {
        sha: 'e10000001',
        shortSha: 'e100000',
        author: { name: 'TJ Holowaychuk', avatarUrl: 'https://avatars.githubusercontent.com/u/25254' },
        date: '2022-01-05T12:00:00Z',
        message: 'Initial router core and server dispatch',
        filesChanged: [
          { filename: 'lib/express.js', status: 'added', additions: 180, deletions: 0, changes: 180 },
          { filename: 'lib/application.js', status: 'added', additions: 420, deletions: 0, changes: 420 },
          { filename: 'lib/router/index.js', status: 'added', additions: 350, deletions: 0, changes: 350 },
          { filename: 'lib/router/layer.js', status: 'added', additions: 160, deletions: 0, changes: 160 },
          { filename: 'package.json', status: 'added', additions: 55, deletions: 0, changes: 55 },
        ],
      },
      {
        sha: 'e20000002',
        shortSha: 'e200000',
        author: { name: 'Douglas Christopher Wilson', avatarUrl: 'https://avatars.githubusercontent.com/u/67512' },
        date: '2022-06-18T15:00:00Z',
        message: 'feat(request): response formatting, content negotiation and cookies',
        filesChanged: [
          { filename: 'lib/request.js', status: 'added', additions: 390, deletions: 0, changes: 390 },
          { filename: 'lib/response.js', status: 'added', additions: 540, deletions: 0, changes: 540 },
          { filename: 'lib/utils.js', status: 'added', additions: 180, deletions: 0, changes: 180 },
          { filename: 'lib/middleware/init.js', status: 'added', additions: 70, deletions: 0, changes: 70 },
          { filename: 'lib/middleware/query.js', status: 'added', additions: 65, deletions: 0, changes: 65 },
        ],
      },
      {
        sha: 'e30000003',
        shortSha: 'e300000',
        author: { name: 'Linus Unnebäck', avatarUrl: 'https://avatars.githubusercontent.com/u/189580' },
        date: '2023-04-10T14:20:00Z',
        message: 'perf: optimize routing regex match and layer pipeline',
        filesChanged: [
          { filename: 'lib/router/route.js', status: 'added', additions: 230, deletions: 0, changes: 230 },
          { filename: 'lib/router/index.js', status: 'modified', additions: 95, deletions: 40, changes: 135 },
          { filename: 'lib/router/layer.js', status: 'modified', additions: 45, deletions: 15, changes: 60 },
          { filename: 'test/app.router.js', status: 'added', additions: 320, deletions: 0, changes: 320 },
        ],
      },
      {
        sha: 'e40000004',
        shortSha: 'e400000',
        author: { name: 'Wes Todd', avatarUrl: 'https://avatars.githubusercontent.com/u/1027776' },
        date: '2024-02-12T19:00:00Z',
        message: 'release: express 5.0 security patches and modern promises',
        filesChanged: [
          { filename: 'lib/application.js', status: 'modified', additions: 80, deletions: 30, changes: 110 },
          { filename: 'lib/router/index.js', status: 'modified', additions: 110, deletions: 25, changes: 135 },
          { filename: 'lib/view.js', status: 'added', additions: 210, deletions: 0, changes: 210 },
          { filename: 'History.md', status: 'added', additions: 450, deletions: 0, changes: 450 },
        ],
      },
    ],
  },
};
